import { Button, VerticalBox, TextEdit, LineEdit, ComboBox, CheckBox, HorizontalBox } from "std-widgets.slint";
import { Buttoner, CalculateLineEdit, CalculateText } from "my-components.slint";

export struct Row  {
    name: string,
    value: float,
    checked: bool,
    timespan: string,
    to_delete: bool,
}

export component AppWindow inherits Window {
    property <color> first_back: #242a3b;
    property <color> second_back: #39516e;
    property <color> third_back: #3c75aa;
    property <color> font_color: #ffffffcc;
    property <length> border_radius_val: 10px;

    in-out property <int> active-tab: 0;

    preferred-height: 380px;
    min-width: 550px;

    icon: @image-url("icons/graph.svg");
    background: @linear-gradient(135deg, first_back 15%, second_back 50%, third_back 100%);
    GridLayout {
        Row {
            HorizontalLayout { // Title 
                padding: 3px;
                spacing: root.width / 6;
                height: 60px;
                Text {
                    text: "Image Converter";
                    preferred-height: root.height / 3;
                    color: font_color;
                    font-italic: true;
                    font-size: 35px;
                    vertical-alignment: top;
                    horizontal-alignment: center;
                }
            }
        }

        VerticalLayout {
            min-width: parent.width;
            HorizontalLayout {
                Rectangle {
                    background: red;
                }

                Rectangle {
                    background: blue;
                }
            }

            property <length> box_width: 30px;

            HorizontalLayout {
                height: 35px;
                spacing: 5px;
                padding: 5px;
                Rectangle {
                    width: box_width;
                    background: #2e3440;
                }

                Rectangle {
                    width: box_width;
                    background: #3b4252;
                }

                Rectangle {
                    width: box_width;
                    background: #434c5e;
                }

                Rectangle {
                    width: box_width;
                    background: #4c566a;
                }

                Rectangle {
                    width: box_width;
                    background: #1D252F;
                }

                Rectangle {
                    width: box_width;
                    background: #81A1C1;
                }

                Rectangle {
                    width: box_width;
                    background: #ECEFF4;
                }

                Rectangle {
                    width: 60px;
                }

                Buttoner {
                    text: "Preview image";
                }
            }

            HorizontalLayout {
                padding: 5px;
                spacing: 5px;
                height: 30px;
                CheckBox {
                    width: box_width;
                }

                CheckBox {
                    width: box_width;
                }

                CheckBox {
                    width: box_width;
                }

                CheckBox {
                    width: box_width;
                }

                CheckBox {
                    width: box_width;
                }

                CheckBox {
                    width: box_width;
                }

                CheckBox {
                    width: box_width;
                }
            }

            HorizontalLayout {
                spacing: 1px;
                Buttoner {
                    border-radius: 1px;

                    text: "Save Image";
                }

                Buttoner {
                    border-radius: 1px;
                    text: "Load Image";
                }

                Buttoner {
                    border-radius: 1px;

                    text: "Exit";
                }
            }
            // tab_bar := HorizontalLayout {
            //     // spacing: 1px;
            //     Buttoner {
            //         border-radius: 1px;
            //         text: "Add new";
            //         clicked => {
            //             root.active-tab = 0;
            //         }
            //     }

            //     Buttoner {
            //         border-radius: 1px;
            //         text: "Calculate";
            //         clicked => {
            //             root.active-tab = 1;
            //         }
            //     }

            //     Buttoner {
            //         border-radius: 1px;
            //         text: "Fuel cost  ";
            //         clicked => {
            //             root.active-tab = 2;
            //         }
            //     }
            // }
        }
    }
}

export component color_box inherits CheckBox {
    toggled => {
    }
}
