import { Button, VerticalBox, TextEdit, LineEdit, ComboBox, CheckBox, HorizontalBox } from "std-widgets.slint";
import { Buttoner, CalculateLineEdit, CalculateText } from "my-components.slint";


export component ColorBox inherits CheckBox {
    in-out property <bool> isSelected: false;
    width: 30px;
    toggled() => {
        isSelected = self.checked;
    }
    text: self.checked ? "1" : "0";
}

export component AppWindow inherits Window {
    property <color> first_back: #242a3b;
    property <color> second_back: #39516e;
    property <color> third_back: #3c75aa;
    property <color> font_color: #ffffffcc;
    property <length> border_radius_val: 10px;

    in-out property <int> active-tab: 0;

    in-out property <string> input_img_dir;
    in-out property <string> input_proxy_img_dir;
    in-out property <string> output_img_dir;
    in-out property <string> output_proxy_img_dir;

    callback load-image(string);
    callback save-image(string);
    callback preview-image(string);
    callback pick-colors([bool]);
    in-out property <[bool]> selection: [false, false, false, false, false, false, false];
    preferred-height: 420px;
    min-width: 550px;
    min-height: 400px;

    background: @linear-gradient(135deg, first_back 15%, second_back 50%, third_back 100%);
    GridLayout {
        Row {
            HorizontalLayout { // Title 
                padding: 3px;
                spacing: root.width / 6;
                height: 60px;
                Text {
                    text: "Image Converter";
                    preferred-height: root.height / 3;
                    color: font_color;
                    font-italic: true;
                    font-size: 35px;
                    vertical-alignment: top;
                    horizontal-alignment: center;
                }
            }
        }

        VerticalLayout {
            min-width: parent.width;
            HorizontalLayout {
                padding: 2px;
                spacing: 10px;
                Image {
                    source: @image-url("../showcase/nord-lion.jpg");
                }

                // Image {
                //     source: @image-url("../showcase/nord-ubuntu.jpg");
                // }

                    CalculateText {
                    width: 100px;
                    text_value: root.selection[0] ? "true" : "false";
                }
            }

            property <length> box_width: 30px;

            HorizontalLayout {
                height: 35px;
                spacing: 5px;
                padding: 5px;
                Rectangle {
                    width: box_width;
                    background: #1D252F;
                }

                Rectangle {
                    width: box_width;
                    background: #2e3440;
                }

                Rectangle {
                    width: box_width;
                    background: #3b4252;
                }

                Rectangle {
                    width: box_width;
                    background: #434c5e;
                }

                Rectangle {
                    width: box_width;
                    background: #4c566a;
                }

                Rectangle {
                    width: box_width;
                    background: #81A1C1;
                }

                Rectangle {
                    width: box_width;
                    background: #ECEFF4;
                }

                Rectangle {
                    width: 60px;
                }

                preview_button := Buttoner {
                    text: "Preview image";
                }
            }

            HorizontalLayout {
                padding-left: 12px;
                padding: 5px;
                spacing: 5px;
                height: 30px;
                ColorBox {
                    isSelected: root.selection[0];
                }

                ColorBox {
                    isSelected: root.selection[1];
                }

                ColorBox {
                    isSelected: root.selection[2];
                }

                ColorBox {
                    isSelected: root.selection[3];
                }

                ColorBox {
                    isSelected: root.selection[4];
                }

                ColorBox {
                    isSelected: root.selection[5];
                }

                ColorBox {
                    isSelected: root.selection[6];
                }
            }

            HorizontalLayout {
                spacing: 1px;
                save_button := Buttoner {
                    border-radius: 1px;
                    text: "Save Image";
                }

                load_button := Buttoner {
                    border-radius: 1px;
                    text: "Load Image";
                }

                exit_button := Buttoner {
                    border-radius: 1px;
                    text: "Exit";
                }
            }
        }
    }
}
